imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            channels: ['!event', '!doctrine']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

swiftmailer:
    delivery_addresses: ['da0590625b-a9b35c@inbox.mailtrap.io']
    spool:     { type: memory }
    transport: smtp
    host:      smtp.mailtrap.io
    username:  b254a121cdfa65
    password:  affe6c3b1f575c
    auth_mode: cram-md5
    port: 2525

#Doctrine
parameters:
    database_host: 127.0.0.1
    database_name: TP004
    database_user: root
    database_password: troiswa

#Alice - fixtures
hautelook_alice:
    db_drivers:
        orm: ~          # Enable Doctrine ORM if is registered
    locale: en_US       # Locale to used for faker; must be a valid Faker locale otherwise will fallback to en_US
    seed: 1             # A seed to make sure faker generates data consistently across runs, set to null to disable
    persist_once: false # Only persist objects once if multiple files are passed
    loading_limit: 5    # Maximum number of time the loader will try to load the files passed